name: WPCS Check

on:
  push:
    branches: [ master, develop, test ]
  pull_request:
    branches: [ master, develop, test ]

jobs:
  wpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # or your required PHP version

    - name: Install dependencies
      run: composer install

    - name: Run WPCS check
      run: composer run phpcs
